language: ruby
cache: bundler
rvm:
  - 2.4.2

install:
  - bundle install --without production
  - yarn

env:
  global:
    # in TravisCI settings, set CCKEY to your CodeClimate Test Reporter ID:
    - CC_TEST_REPORTER_ID=$CCKEY
    - CCTR=./cc-test-reporter
    # set to whatever timezone your app assumes from this list:
    # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    - TZ=America/Los_Angeles

# steps to run BEFORE the test run
before_script:
  # create config/application.yml (sensitive API keys etc) from config/application.yml.asc
  # IMPORTANT: you must MANUALLY set correct value of encryption KEY in Travis settings for your project --
  # DO NOT expose that value here!
  # install CodeClimate test reporter and tell it we are starting a test run
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  - chmod +x $CCTR
  - $CCTR before-build

script:
  #set up the database
  - bundle exec rake db:setup
  - bundle exec rake webpacker:compile
  # - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
  # run Cucumber scenarios, and capture coverage. --strict means undefined steps result in a failure.
  - bundle exec cucumber --strict
  - bundle exec rake spec
  - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json

after_script:
  # combine coverage from all suites, and upload to CodeClimate
  - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
  - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT
  # just in case, be paranoid and remove sensitive config info file
  - rm -f config/application.yml
